import { Quintessential, Geist } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import LazyAnimations from "@/app/lazy-motion";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const quintessential = Quintessential({
	variable: "--font-quintessential",
	subsets: ["latin"],
	style: "normal",
	display: "swap",
	weight: "400",
	preload: true,
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body
				className={`${geistSans.variable} ${quintessential.variable} antialiased`}
			>
				<LazyAnimations>{children}</LazyAnimations>
			</body>
		</html>
	);
}
